# Generated by Django 5.0.3 on 2024-10-31 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('payment_date', models.DateField(verbose_name='تاريخ الدفع')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدا'), ('Bank Trasfer', 'تحويل بنكي'), ('Credit Card', 'بطاقة انتمان')], max_length=255, verbose_name='طريقة الدفع')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('paid', 'مدفوع'), ('cancelled', 'الغاء')], max_length=255, verbose_name='حالة الدفع')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentManager.lease', verbose_name='عقد الإيجار')),
            ],
        ),
    ]
